# 引入第三方的插件
# 配置文件格式:
# 仓库地址 | 存储目录名(可选) | 分支/Tag(可选) | feeds清理关键词(可选，多个用空格隔开)
# 不填留空即可 | |
# ==================================================================================
https://github.com/destan19/OpenAppFilter.git | OpenAppFilter | | appfilter oaf open-app-filter

https://github.com/stevenjoezhang/luci-app-adguardhome.git | luci-app-adguardhome | | adguardhome

https://github.com/sbwml/luci-app-mosdns.git | luci-app-mosdns | | mosdns

https://github.com/wwng2333/luci-app-qsdk-accel.git | luci-app-qsdk-accel | | qsdk-accel